name: test

on:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-26.04-arm
    steps:
      - uses: actions/checkout@v7
      - run: git ls-files -z '*.bats' | xargs -0 docker run --rm -v "$PWD:/code" bats/bats:1.14.0
